version: '2'

services:
    crossdock:
        image: crossdock/crossdock
        links:
            - go
            - java
            - python
            - node
        environment:
            - WAIT_FOR=go,java,python,node

            - AXIS_CLIENT=go
            - AXIS_S1NAME=go,java,node
            - AXIS_SAMPLED=true
            - AXIS_S2NAME=go,java,node
            - AXIS_S2TRANSPORT=http,tchannel
            - AXIS_S3NAME=go,java,node
            - AXIS_S3TRANSPORT=http,tchannel

            - BEHAVIOR_TRACE=client,s1name,sampled,s2name,s2transport,s3name,s3transport

            - REPORT=compact
    go:
        image: jaegertracing/xdock-go
        ports:
            - "8080-8082"

    python:
        image: jaegertracing/xdock-py
        ports:
            - "8080-8082"

    java:
        image: jaegertracing/xdock-java
        ports:
            - "8080-8082"

    node:
        build:
            context: ..
        ports:
            - "8080-8082"
